DjangoProject/DjangoProject/urls.py
from django.urls import path,include
from django.contrib import admin

urlpatterns = [
    # path(r'^admin/', admin.site.urls),
    path('ueditor/', include('ueditor.urls')),
    path('myadmin/', include('myadmin.urls')),
    path('',include('myhome.urls')),
]

DjangoProject/myadmin/urls.py
from django.conf.urls import url
from .views import IndexViews, UsersViews, CatesViews, GoodsViews,OrderViews

urlpatterns = [
    url(r'^$',IndexViews.index,name="myadmin_index"),

    # 登录页
    url(r'^login/$',IndexViews.myadmin_login,name="myadmin_login"),
    url(r'^dologin/$',IndexViews.myadmin_dologin,name="myadmin_dologin"),
    url(r'^verifycode/$', IndexViews.verifycode, name="myadmin_vcode"),
    url(r'^logout/$',IndexViews.myadmin_logout,name="myadmin_logout"),

    url(r'^user/add/$',UsersViews.user_add,name="myadmin_user_add"),
    url(r'^user/insert/$',UsersViews.user_insert,name="myadmin_user_insert"),

    url(r'^user/index/$',UsersViews.user_index,name="myadmin_user_index"),
    url(r'^user/edit/$',UsersViews.user_edit,name="myadmin_user_edit"),

    url(r'^user/setstatus/$',UsersViews.user_set_status,name="myadmin_user_set_status"),

    # 分类管理
    url(r'^cate/add/$', CatesViews.cate_add, name="myadmin_cate_add"),
    url(r'^cate/index/$',CatesViews.cate_index,name="myadmin_cate_index"),
    url(r'^cate/del/$', CatesViews.cate_del, name="myadmin_cate_del"),
    url(r'^cate/edit/$',CatesViews.cate_edit,name="myadmin_cate_edit"),


    url(r'^goods/add/$',GoodsViews.goods_add,name="myadmin_goods_add"),
    url(r'^goods/insert/$',GoodsViews.goods_insert,name="myadmin_goods_insert"),
    url(r'^goods/index/$',GoodsViews.goods_index,name="myadmin_goods_index"),
    url(r'^goods/edit/$', GoodsViews.goods_edit, name="myadmin_goods_edit"),

    url(r'^goods/setstatus/$',GoodsViews.goods_set_status,name="goods_set_status"),

    url(r'^order/index/$', OrderViews.order_index, name="order_index"),
    url(r'^orders/setstatus/$',OrderViews.orders_set_status,name="orders_set_status"),
    url(r'^orders/setpaytype/$', OrderViews.orders_set_paytype, name="orders_set_paytype"),
    url(r'^orders/delete/$', OrderViews.myadmin_order_del, name="myadmin_order_del"),



]

DjangoProject/myhome/urls.py
from django.conf.urls import url, re_path
from . views import IndexViews,LoginViews,CartViews,OrderViews,CenterViews

urlpatterns = [
    # 首页
    url(r'^$',IndexViews.myhome_index,name="myhome_index"),
    # 列表
    re_path(r'^list/(?P<cid>[0-9]+)',IndexViews.myhome_list,name="myhome_list"),
    # 详情
    url(r'^info/',IndexViews.myhome_info,name="myhome_info"),

    # 登录
    url(r'^login/',LoginViews.myhome_login,name="myhome_login"),
    url(r'^dologin/',LoginViews.myhome_dologin,name="myhome_dologin"),
    url(r'^logout/',LoginViews.myhome_logout,name="myhome_logout"),

    # 注册
    url(r'^register/',LoginViews.myhome_register,name="myhome_register"),
    url(r'^doregister/',LoginViews.myhome_doregister,name="myhome_doregister"),

    # 短信发送
    url(r'^sendMsg/',LoginViews.myhome_sendMsg,name="myhome_sendMsg"),

    # 购物车 增 删 改 查
    url(r'^cart/add/',CartViews.myhome_cart_add,name="myhome_cart_add"),
    url(r'^cart/index/', CartViews.myhome_cart_index, name="myhome_cart_index"),
    url(r'^cart/del/', CartViews.myhome_cart_del, name="myhome_cart_del"),
    url(r'^cart/clear/', CartViews.myhome_cart_clear, name="myhome_cart_clear"),
    url(r'^cart/edit/', CartViews.myhome_cart_edit, name="myhome_cart_edit"),

    # 订单  确认订单,提交订单,订单支付
    url(r'^order/confirm/', OrderViews.myhome_order_confirm, name="myhome_order_confirm"),
    url(r'^order/create/', OrderViews.myhome_order_create, name="myhome_order_create"),
    url(r'^order/pay/', OrderViews.myhome_order_pay, name="myhome_order_pay"),

    # 个人中心  我的订单 个人信息 地址管理
    url(r'^center/order/',CenterViews.myhome_center_order,name="myhome_center_order"),
]

DjangoProject/myadmin/models.py
from django.db import models

# Create your models here.

# 定义会员模型
class Users(models.Model):
    nikename = models.CharField(max_length=20,null=True)
    password = models.CharField(max_length=100)
    # phone = models.CharField(max_length=11,unique=True)
    phone = models.CharField(max_length=11)
    email = models.CharField(max_length=100)
    age = models.IntegerField(null=True)
    pic_url = models.CharField(max_length=100)
    SEX_CHOICES = (
        (0, '女'),
        (1, '男'),
    )
    sex = models.CharField(max_length=1,null=True,choices=SEX_CHOICES)
    # 0 正常  1禁用  2 删除 ....
    status = models.IntegerField(default=0)
    addtime = models.DateTimeField(auto_now_add=True)


# 商品分类模型
class Cates(models.Model):
    name = models.CharField(max_length=20)
    pid = models.IntegerField()
    path = models.CharField(max_length=50)
    ''' 无限分类
        id  name    pid  path
        1    服装     0    0,
        2    男装     1    0,1,
        3    西服     2    0,1,2,
        4    休闲西服  3    0,1,2,3,
        5    女装     1    0,1,
        6    裙子     5    0,1,5,
        7    超短裙    6   0,1,5,6,
    '''

# 商品模型
class Goods(models.Model):
    # id 所属分类,商品名,图片,添加时间,销量
    cateid = models.ForeignKey(to="Cates", to_field="id", on_delete=models.CASCADE)
    goodsname = models.CharField(max_length=50)
    title = models.CharField(max_length=255)
    price = models.FloatField()
    goodsnum = models.IntegerField()
    pic_url = models.CharField(max_length=255)
    goodsinfo = models.TextField()
    ordernum =  models.IntegerField(default=0)
    clicknum = models.IntegerField(default=0)
    # 0 新品,1热卖,2推荐,3下架
    status = models.IntegerField(default=0)
    addtime = models.DateTimeField(auto_now_add=True)

# 购物车 模型
class Cart(models.Model):
    # id  用户 uid   商品 goodsid 数量 num
    uid = models.ForeignKey(to="Users", to_field="id",on_delete=models.CASCADE)
    goodsid = models.ForeignKey(to="Goods", to_field="id",on_delete=models.CASCADE)
    num = models.IntegerField()

# 订单
class Order(models.Model):
    uid = models.ForeignKey(to="Users", to_field="id",on_delete=models.CASCADE)
    username = models.CharField(max_length=20)
    phone = models.CharField(max_length=11)
    address = models.CharField(max_length=255)
    totalprice = models.FloatField()
    # 0 未支付, 1已支付, 2已发货  3已收货  4已评价  5取消 ...
    status = models.IntegerField(default=0)
    # 0 支付宝  1 微信 2 银联  3 其它  4货到付款...
    paytype = models.IntegerField(default=0)
    addtime = models.DateTimeField(auto_now_add=True)
    paytime = models.DateTimeField(null=True)


# 订单详情
class OrderInfo(models.Model):
    orderid = models.ForeignKey(to="Order", to_field="id",on_delete=models.CASCADE)
    goodsid = models.ForeignKey(to="Goods", to_field="id",on_delete=models.CASCADE)
    num = models.IntegerField()

'''
# 订单
    id订单号 uid用户 收货人,收货地址,收货电话,总价,状态 支付方式 ,下单时间,支付时间
    100011       189     
# 订单详情
    orderid   goodsid   num  price购买时的单价
    100011     12       1
    100011     18       3
'''

DjangoProject/myadmin/views/CatesViews.py
from django.shortcuts import render, reverse
from django.http import HttpResponse,JsonResponse
from .. models import Cates


# 分类 列表
def cate_index(request):
    # 获取数据
    data = get_cates_all()
    # 分配数据
    context = {'catelist':data}
    # 加载模板
    return render(request,'myadmin/cates/index.html',context)

# 分类 添加
def cate_add(request):
    if request.method == 'POST':
        # 接受数据
        data = {}
        data['name'] = request.POST.get('name')
        data['pid'] = request.POST.get('pid')

        # 判断是否为顶级分类
        if data['pid'] == '0':
            data['path'] = '0,'
        else:
            # 获取当前父级的path路径,
            pob = Cates.objects.get(id=data['pid'])
            # 拼接当前数据的path
            data['path'] = pob.path+data['pid']+','

        # 数据 入库
        ob = Cates(**data)
        ob.save()

        return HttpResponse('<script>alert("添加成功");location.href="'+reverse('myadmin_cate_index')+'";</script>')
        #return HttpResponse('aaaaaaa')

    else:
        # 显示表单
        # 获取当前已有的 分类
        catelist = get_cates_all()
        #catelist = Cates.objects.all()
        # 分配数据
        context = {'catelist':catelist}
        # 加载一个模板
        return render(request,'myadmin/cates/add.html',context)

# 封装函数.格式化获取分类数据
def get_cates_all():
    # 获取所有的分类
    # data = Cates.objects.all()
    # select *,concat(path,id) as paths from myadmin_cates order by paths;
    data = Cates.objects.extra(select = {'paths':'concat(path,id)'}).order_by('paths')
    # 处理数据的顺序,缩进,及父级名
    for x in data:
        l = x.path.count(',')-1 # 0,1,2,
        x.sub = l*'|----'
        if x.pid == 0:
            x.pname = '顶级分类'
        else:
            pob = Cates.objects.get(id=x.pid)
            x.pname = pob.name
        # print(x.name,l)
    return data

# 分类删除
def cate_del(request):
    cid = request.GET.get('cid')
    # 判断当前分类下是否还有子类
    res = Cates.objects.filter(pid=cid).count()
    if res:
        # 有子类
        return JsonResponse({'msg':'当前类下有子类,不能删除','code':1})

    # 判断当前分类下是否有商品发布


    # 执行删除
    ob = Cates.objects.get(id=cid)
    ob.delete()
    return JsonResponse({'msg':'删除成功','code':0})

# 分类 名字修改
def cate_edit(request):
    try:
        # 获取 参数
        cid = request.GET.get('cid')
        newname = request.GET.get('newname')

        # 获取对象
        ob = Cates.objects.get(id=cid)
        ob.name = newname
        # 修改属性
        ob.save()
        data = {'msg':'更新成功','code':0}
    except:
        data = {'msg':'更新失败','code':1}

    # 返回结果
    return JsonResponse(data)

DjangoProject/myadmin/views/GoodsViews.py
from django.shortcuts import render, reverse
from django.http import HttpResponse,JsonResponse

from . CatesViews import get_cates_all
from . UsersViews import uploads_pic
from .. models import Cates, Goods
from DjangoProject.settings import BASE_DIR
import os
from django.contrib.auth.hashers import make_password, check_password

# Create your views here.

# 商品添加 表单
def goods_add(request):
    # 获取当前所有的分类数据
    data = get_cates_all()
    # 分配数据
    context = {'catelist':data}
    # 显示一个添加的表单
    return render(request,'myadmin/goods/add.html',context)

def goods_insert(request):

  try:
      # 接收表单数据
      data = request.POST.dict()
      data.pop('csrfmiddlewaretoken')
      print(data)
      # 处理 分类对象
      data['cateid'] = Cates.objects.get(id=data['cateid'])
      # 判断是否有图片上传
      myfile = request.FILES.get('pic', None)
      if not myfile:
          return HttpResponse('<script>alert("必须上传商品图片");history.back(-1);</script>')
      # 处理  上传的文件
      data['pic_url'] = uploads_pic(myfile)

      # 执行添加
      ob = Goods(**data)
      ob.save()

      return HttpResponse('<script>alert("商品添加成功");location.href="'+reverse('myadmin_goods_index')+'";</script>')

  except:
      pass

  return HttpResponse('<script>alert("商品添加失败");history.back(-1);</script>')


def goods_index(request):
    # 获取所有的商品对象
    data = Goods.objects.all()

    # 获取搜索条件
    types = request.GET.get('types', None)
    keywords = request.GET.get('keywords', None)
    # 判断是否搜索
    if types == 'all':
        from django.db.models import Q
        data = data.filter(Q(id__contains=keywords) | Q(goodsname__contains=keywords) | Q(title__contains=keywords))
    elif types:
        search = {types + '__contains': keywords}
        data = data.filter(**search)

    # 导入分页类
    from django.core.paginator import Paginator
    # 实例化分页类，第二个参数是每页多少条
    p = Paginator(data, 6)
    # 获取当前的页码数
    pageindex = request.GET.get('page', 1)
    # 获取当前页的数据
    goodslist = p.page(pageindex)

    # 获取所有的页码
    # p.count 一共多少条
    # pages = p.page_range #迭代器(range(,))
    # pages = p.num_pages #分了多少页

    context = {'goodslist': goodslist}

    # 加载模板
    return render(request, 'myadmin/goods/index.html', context)

def goods_edit(request):
    # 接受商品id
    uid = request.GET.get('uid')
    # 获取当前会员对象
    gd = Goods.objects.get(id=uid)

    # 判断当前的请求方式
    if request.method == 'POST':

        # 判断头像是否更新
        myfile = request.FILES.get('pic', None)
        if myfile:
            # 如果有新头像上传,则先删除原头像图片,
            os.remove(BASE_DIR + gd.pic_url)
            # /static/uploads/1545033786.7237682.png
            # ./static/uploads/1545033786.7237682.png
            # /home/yc/py16/py16-project/web
            # 在上传新的头像
            gd.pic_url = uploads_pic(myfile)

        # 更新其它字段
        gd.goodsname = request.POST.get('goodsname')
        gd.title = request.POST.get('title')
        gd.price = request.POST.get('price')
        gd.goodsnum = request.POST.get('goodsnum')
        gd.goodsinfo = request.POST.get('goodsinfo')
        gd.save()
        return HttpResponse('<script>alert("更新成功");location.href="' + reverse('myadmin_goods_index') + '";</script>')

    else:
        # 显示编辑表单
        context = {'uinfo': gd}
        return render(request, 'myadmin/goods/edit.html', context)

def goods_set_status(request):
    # 通过uid获取当前商品对象
    ob = Goods.objects.get(id=request.GET.get('uid'))
    ob.status = request.GET.get('status')
    ob.save()
    return JsonResponse({'msg': '状态更新成功', 'code': 0})

DjangoProject/myadmin/views/IndexViews.py
from django.shortcuts import render,reverse
from django.http import HttpResponse

# Create your views here.

def index(request):
    
    return render(request,'myadmin/index.html')

# 登录页
def myadmin_login(request):
    # 加载页面
    return render(request, 'myadmin/login.html')

# 处理登录
def myadmin_dologin(request):
    # 检测验证是否正确
    if request.session.get('verifycode').upper() != request.POST.get('vcode').upper():
        return HttpResponse('<script>alert("验证码错误");location.href="/myadmin/login/"</script>')

    # 判断用户名是否存在,检验密码是否正确
    if request.POST['username'] == 'admin' and request.POST['password'] == '123456':
        # 成功,把用户信息记录在session中
        request.session['AdminUser'] = {'username': 'admin', 'uid': 10}
        return HttpResponse('<script>alert("欢迎登录");location.href="'+reverse('myadmin_index')+'";</script>')

    return HttpResponse('<script>alert("账号或密码错误");location.href="'+reverse('myadmin_login')+'";</script>')

# 验证码
def verifycode(request):
    #引入绘图模块
    from PIL import Image, ImageDraw, ImageFont
    #引入随机函数模块
    import random
    #定义变量，用于画面的背景色、宽、高
    bgcolor = (random.randrange(20, 100), random.randrange(
        20, 100), 255)
    width = 100
    height = 25
    #创建画面对象
    im = Image.new('RGB', (width, height), bgcolor)
    #创建画笔对象
    draw = ImageDraw.Draw(im)
    #调用画笔的point()函数绘制噪点
    for i in range(0, 100):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)
    #定义验证码的备选值
    str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
    # str1 = '123456789'
    #随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str1[random.randrange(0, len(str1))]
    #构造字体对象
    font = ImageFont.truetype('simhei.ttf', 23)
    #构造字体颜色
    fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
    #绘制4个字
    draw.text((5, 2), rand_str[0], font=font, fill=fontcolor)
    draw.text((25, 2), rand_str[1], font=font, fill=fontcolor)
    draw.text((50, 2), rand_str[2], font=font, fill=fontcolor)
    draw.text((75, 2), rand_str[3], font=font, fill=fontcolor)
    #释放画笔
    del draw
    #存入session，用于做进一步验证
    request.session['verifycode'] = rand_str
    #内存文件操作
    import io
    buf = io.BytesIO()
    #将图片保存在内存中，文件类型为png
    im.save(buf, 'png')
    #将内存中的图片数据返回给客户端，MIME类型为图片png
    return HttpResponse(buf.getvalue(), 'image/png')


# 退出登录
def myadmin_logout(request):
    del request.session['AdminUser']

    return HttpResponse('<script>alert("退出成功");location.href="'+reverse('myadmin_login')+'";</script>')

DjangoProject/myadmin/views/OrderViews.py
from django.shortcuts import render, reverse
from django.http import HttpResponse,JsonResponse
from .. models import Order

def order_index(request):
    # 获取所有的商品对象
    data = Order.objects.all()

    # 获取搜索条件
    types = request.GET.get('types', None)
    keywords = request.GET.get('keywords', None)
    # 判断是否搜索
    if types == 'all':
        from django.db.models import Q
        data = data.filter(Q(id__contains=keywords) | Q(username__contains=keywords) | Q(phone__contains=keywords))
    elif types:
        search = {types + '__contains': keywords}
        data = data.filter(**search)

    # 导入分页类
    from django.core.paginator import Paginator
    # 实例化分页类，第二个参数是每页多少条
    p = Paginator(data, 15)
    # 获取当前的页码数
    pageindex = request.GET.get('page', 1)
    # 获取当前页的数据
    orderslist = p.page(pageindex)

    # 获取所有的页码
    # p.count 一共多少条
    # pages = p.page_range #迭代器(range(,))
    # pages = p.num_pages #分了多少页

    context = {'orderslist': orderslist}

    # 加载模板
    return render(request, 'myadmin/order/index.html', context)

def orders_set_status(request):
    # 通过uid获取当前商品对象
    ob = Order.objects.get(id=request.GET.get('uid'))
    ob.status = request.GET.get('status')
    ob.save()
    return JsonResponse({'msg': '支付状态更新成功', 'code': 0})

def orders_set_paytype(request):
    # 通过uid获取当前商品对象
    ob = Order.objects.get(id=request.GET.get('uid'))
    ob.paytype = request.GET.get('paytype')
    ob.save()
    return JsonResponse({'msg': '支付方式状态更新成功', 'code': 0})

def myadmin_order_del(request):
    oid = request.GET.get('oid')
    # 判断当前分类下是否还有子类
    res = Order.objects.get(id=oid)
    res.delete()
    return JsonResponse({'msg': '删除成功', 'code': 0})

DjangoProject/templates/myadmin/cates/add.html
{% extends 'myadmin/index.html' %}

{% block title %}
<title>后台商品分类添加</title>
{% endblock %}


{% block con %}
<div class="row-content am-cf">
    <div class="row">
        <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
            <div class="widget am-cf">
                <div class="widget-head am-cf">
                    <div class="widget-title am-fl">
                        商品分类添加
                    </div>
                    <div class="widget-function am-fr">
                        <a href="javascript:;" class="am-icon-cog">
                        </a>
                    </div>
                </div>
                <div class="widget-body am-fr">
                    <form action="{% url 'myadmin_cate_add' %}" method="POST" enctype="multipart/form-data" class="am-form tpl-form-line-form">
                        {% csrf_token %}

                        <div class="am-form-group">
                            <label for="user-name" class="am-u-sm-3 am-form-label">
                                所属分类
                            </label>
                            <select name="pid" data-am-selected="{btnSize: 'sm'}" style="display: none;">
                              <option value="0" >顶级分类</option>
                              {% for v in catelist %}
                              <option value="{{ v.id }}" >{{ v.sub }}{{ v.name }}</option>
                              {% endfor %}
                            </select>
                        </div>


                        <div class="am-form-group">
                            <label for="user-name" class="am-u-sm-3 am-form-label">
                                分类名称
                            </label>
                            <div class="am-u-sm-9">
                                <input type="text" name="name" class="tpl-form-input"
                                 placeholder="分类名称">
                            </div>
                        </div>


                        <div class="am-form-group">
                            <div class="am-u-sm-9 am-u-sm-push-3">
                                <button class="am-btn am-btn-primary tpl-btn-bg-color-success ">
                                    提交
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

DjangoProject/templates/myadmin/cates/index.html
{% extends 'myadmin/index.html' %}

{% block title %}
<title>后台商品分类列表</title>
{% endblock %}

{% block con %}
<div class="row-content am-cf">
    <div class="row">
        <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
            <div class="widget am-cf">
                <div class="widget-head am-cf">
                    <div class="widget-title  am-cf">商品分类列表</div>

                </div>
                <div class="widget-body  am-fr">

                    <div class="am-u-sm-12 am-u-md-6 am-u-lg-6">
                        <div class="am-form-group">
                            <div class="am-btn-toolbar">
                                <div class="am-btn-group am-btn-group-xs">
                                    <a href="{% url 'myadmin_cate_add' %}" class="am-btn am-btn-default am-btn-success"><span class="am-icon-plus"></span> 新增</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="am-u-sm-12">
                        <table width="100%" class="am-table am-table-compact am-table-striped tpl-table-black ">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>分类名</th>
                                    <th>所属父级</th>
                                    <th>该类下的商品数量</th>
                                    <th>Path路径</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for v in catelist %}
                                <tr>
                                    <td class="am-text-middle">{{ v.id }}</td>
                                    <td class="am-text-middle cate_name">{{ v.sub }}<span cid="{{ v.id }}">{{ v.name }}</span></td>
                                    <td class="am-text-middle">{{ v.pname }}</td>
                                    <td class="am-text-middle">{{ v.goods_set.count|default:'无' }}</td>
                                    <td class="am-text-middle">{{ v.path }}</td>
                                    
                                    <td class="am-text-middle">
                                        <div class="tpl-table-black-operation">
                                             <a href="javascript:void(0)" cid="{{ v.id }}" class="removeCate tpl-table-black-operation-del">
                                                <i class="am-icon-pencil"></i> 删除
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
            
                                <!-- more data -->
                            </tbody>
                        </table>
                    </div>
                    <div class="am-u-lg-12 am-cf">

                        <div class="am-fr">
                            <ul class="am-pagination tpl-pagination">

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    // $(this) window 对象   窗口对象  --> 文档对象(DOM),location(地址对象) history(历史对象)

    // 分类编辑
    $('.cate_name').dblclick(function(){
        // 1 绑定双击事件,获取name换成input
        var span = $(this).find('span')
        // 获取当前分类名字
        var catename = span.text()
        // 创建一个 input
        var inp = $('<input type="text" style="color:black;" value="'+catename+'">')
        // 把分类名换成input
        $(this).find('span').html(inp)
        // 让input中的值 处于选中状态
        inp.select()
        // 获取当前选择的元素的 分类 id
        var cid = span.attr('cid')

        // 2,给input绑定丧失焦点事件,判断是否更新了name,发送ajax去修改
        inp.blur(function(){
            // 获取当前新的name
            var newname = $(this).val()
            // 判断当前的值和原来的值是否一样
            if(newname == catename){
                // 不需要修改,恢复原样
                span.html(catename)
            }else{
                // 需要发送ajax去更新
                $.get('{% url 'myadmin_cate_edit' %}',{'cid':cid,'newname':newname},function(data){
                    // 判断是否更新成功
                    if(data['code'] == 0){
                        span.html(newname)
                        alert(data['msg'])
                    }
                },'json')
            }
        })
    })

    // 删除
    $('.removeCate').click(function(){
        // 获取当前选择的分类的id
        var cid = $(this).attr('cid')
        var a = $(this)
        // 发送ajax请求.到后台执行删除
        $.get('{% url 'myadmin_cate_del' %}',{'cid':cid},function(data){
            // 判断当前的返回值
            if(data['code'] == 0){
                // 删除成功
                // $(this).parents('tr').remove()
                //  此处的 $(this) 是谁? ajax对象 XMLHttpRequest
                a.parents('tr').remove()
            }
            alert(data['msg'])
        },'json')
        

    })
</script>
{% endblock %}